substitutions:
  device_name: diesel-heater
  friendly_name: Diesel Heater
  device_description: "Webasto"
  heater_address: 0xCA00445B

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: "radzu.diesel_heater"
    version: "0.1"
  includes:
    - diesel_pilot_component.h

  on_boot:
    priority: 800 
    then:
      - lambda: |-
          auto *diesel = new DieselPilotComponent();
          diesel->set_heater_address(${heater_address});
          App.register_component(diesel);
          diesel->voltage_sensor  = id(heater_voltage);
          diesel->ambient_sensor  = id(heater_ambient);
          diesel->case_sensor     = id(heater_case);
          diesel->setpoint_sensor = id(heater_setpoint);
          diesel->pump_sensor     = id(heater_pump);
          diesel->rssi_sensor     = id(heater_rssi);
          diesel->state_text      = id(heater_state);
          diesel->mode_text       = id(heater_mode);

# ---------- Board ---------

esp32:
  variant: esp32
  board: esp32dev
  framework:
    type: arduino

# ---------- Network ---------

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    priority: 1.0

  - ssid: !secret wifi2_ssid
    password: !secret wifi2_password 

  manual_ip:
    static_ip: !secret diesel_heater_ip
    gateway: !secret gateway_ip
    subnet: !secret subnet_mask
    dns1: !secret dns_primary
    dns2: !secret dns_secondary

  power_save_mode: none

  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret ap_pw

# ---------- Standard config ---------

logger:

api:
  encryption:
    key: !secret encryption_key
  reboot_timeout: 0s  

web_server:
  port: 80  

captive_portal:
  
ota:
  - platform: esphome
    password: !secret ota_password     
  - platform: web_server

# ---------- Safety & Debug ---------

safe_mode:
  boot_is_good_after: 2min
  num_attempts: 5
  reboot_timeout: 10min

debug:
  update_interval: 30s

# ---------- Status LED ---------

status_led:
  pin:
    number: GPIO13
    inverted: yes

# ---------- Control Buttons ---------

button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic
    icon: mdi:restart

  - platform: template
    name: "${friendly_name} Power"
    on_press:
      then:
        - lambda: |-
            if (DieselPilotComponent::instance != nullptr)
              DieselPilotComponent::instance->send_power();

  - platform: template
    name: "${friendly_name} Up"
    on_press:
      then:
        - lambda: |-
            if (DieselPilotComponent::instance != nullptr)
              DieselPilotComponent::instance->send_up();

  - platform: template
    name: "${friendly_name} Down"
    on_press:
      then:
        - lambda: |-
            if (DieselPilotComponent::instance != nullptr)
              DieselPilotComponent::instance->send_down();

  - platform: template
    name: "${friendly_name} Mode"
    on_press:
      then:
        - lambda: |-
            if (DieselPilotComponent::instance != nullptr)
              DieselPilotComponent::instance->send_mode();

# ---------- Diagnostic Sensors ---------

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal %"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    device_class: ""

  - platform: uptime
    type: timestamp
    name: "Uptime"
    entity_category: diagnostic

  - platform: debug
    free:
      name: "Heap Free"
      entity_category: diagnostic
    loop_time:
      name: "Loop Time"
      entity_category: diagnostic

  - platform: template
    name: "${friendly_name} Voltage"
    id: heater_voltage
    unit_of_measurement: "V"

  - platform: template
    name: "${friendly_name} Ambient"
    id: heater_ambient
    unit_of_measurement: "°C"

  - platform: template
    name: "${friendly_name} Case"
    id: heater_case
    unit_of_measurement: "°C"

  - platform: template
    name: "${friendly_name} Setpoint"
    id: heater_setpoint
    unit_of_measurement: "°C"

  - platform: template
    name: "${friendly_name} Pump"
    id: heater_pump
    unit_of_measurement: "Hz"

  - platform: template
    name: "${friendly_name} RSSI"
    id: heater_rssi
    unit_of_measurement: "dBm"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    mac_address:
      name: "MAC Address"
      entity_category: diagnostic

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    entity_category: diagnostic
    icon: mdi:new-box

  - platform: debug
    reset_reason:
      name: "Reset Reason"
      entity_category: diagnostic

  - platform: template
    name: "${friendly_name} State"
    id: heater_state

  - platform: template
    name: "${friendly_name} Mode"
    id: heater_mode

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Warsaw

# ---------- Main Device Function ---------

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
